export const state = () => ({
  images: [
    { title: 'A Dab of Ink', src: 'A_Dab_of_Ink_card_art.jpg' },
    { title: 'A Mothers Parting Gift', src: 'A_Mothers_Parting_Gift_card_art.jpg' },
    { title: 'Abandoned Wealth', src: 'Abandoned_Wealth_card_art.jpg' },
    { title: 'Akils Prophecy', src: 'Akils_Prophecy_card_art.jpg' },
    { title: 'Alluring Bounty', src: 'Alluring_Bounty_card_art.jpg' },
    { title: 'Alone in the Darkness', src: 'Alone_in_the_Darkness_card_art.jpg' },
    { title: 'Anarchys Price', src: 'Anarchys_Price_card_art.jpg' },
    { title: 'Arrogance of the Vaal', src: 'Arrogance_of_the_Vaal_card_art.jpg' },
    { title: 'Assassins Favour', src: 'Assassins_Favour_card_art.jpg' },
    { title: 'Atziris Arsenal', src: 'Atziris_Arsenal_card_art.jpg' },
    { title: 'Audacity', src: 'Audacity_card_art.jpg' },
    { title: 'Azyrans Reward', src: 'Azyrans_Reward_card_art.jpg' },
    { title: 'Baited Expectations', src: 'Baited_Expectations_card_art.jpg' },
    { title: 'Beauty Through Death', src: 'Beauty_Through_Death_card_art.jpg' },
    { title: 'Blessing of God', src: 'Blessing_of_God_card_art.jpg' },
    { title: 'Blind Venture', src: 'Blind_Venture_card_art.jpg' },
    { title: 'Boon of Justice', src: 'Boon_of_Justice_card_art.jpg' },
    { title: 'Boon of the First Ones', src: 'Boon_of_the_First_Ones_card_art.jpg' },
    { title: 'Boundless Realms', src: 'Boundless_Realms_card_art.jpg' },
    { title: 'Bowyers Dream', src: 'Bowyers_Dream_card_art.jpg' },
    { title: 'Buried Treasure', src: 'Buried_Treasure_card_art.jpg' },
    { title: 'Burning Blood', src: 'Burning_Blood_card_art.jpg' },
    { title: 'Call to the First Ones', src: 'Call_to_the_First_Ones_card_art.jpg' },
    { title: 'Camerias Cut', src: 'Camerias_Cut_card_art.jpg' },
    { title: 'Cartographers Delight', src: 'Cartographers_Delight_card_art.jpg' },
    { title: 'Chaotic Disposition', src: 'Chaotic_Disposition_card_art.jpg' },
    { title: 'Council of Cats', src: 'Council_of_Cats_card_art.jpg' },
    { title: 'Coveted Possession', src: 'Coveted_Possession_card_art.jpg' },
    { title: 'Dark Dreams', src: 'Dark_Dreams_card_art.jpg' },
    { title: 'Dark Temptation', src: 'Dark_Temptation_card_art.jpg' },
    { title: 'Death', src: 'Death_card_art.jpg' },
    { title: 'Deathly Designs', src: 'Deathly_Designs_card_art.jpg' },
    { title: 'Demigods Wager', src: 'Demigods_Wager_card_art.jpg' },
    { title: 'Destined to Crumble', src: 'Destined_to_Crumble_card_art.jpg' },
    { title: 'Diallas Subjugation', src: 'Diallas_Subjugation_card_art.jpg' },
    { title: 'Divine Justice', src: 'Divine_Justice_card_art.jpg' },
    { title: 'Doedres Madness', src: 'Doedres_Madness_card_art.jpg' },
    { title: 'Earth Drinker', src: 'Earth_Drinker_card_art.jpg' },
    { title: 'Echoes of Love', src: 'Echoes_of_Love_card_art.jpg' },
    { title: 'Emperors Luck', src: 'Emperors_Luck_card_art.jpg' },
    { title: 'Emperor of Purity', src: 'Emperor_of_Purity_card_art.jpg' },
    { title: 'Etched in Blood', src: 'Etched_in_Blood_card_art.jpg' },
    { title: 'Forbidden Power', src: 'Forbidden_Power_card_art.jpg' },
    { title: 'Friendship', src: 'Friendship_card_art.jpg' },
    { title: 'Gemcutters Promise', src: 'Gemcutters_Promise_card_art.jpg' },
    { title: 'Gift of the Gemling Queen', src: 'Gift_of_the_Gemling_Queen_card_art.jpg' },
    { title: 'Glimmer of Hope', src: 'Glimmer_of_Hope_card_art.jpg' },
    { title: 'Grave Knowledge', src: 'Grave_Knowledge_card_art.jpg' },
    { title: 'Harmony of Souls', src: 'Harmony_of_Souls_card_art.jpg' },
    { title: 'Her Mask', src: 'Her_Mask_card_art.jpg' },
    { title: 'Heterochromia', src: 'Heterochromia_card_art.jpg' },
    { title: 'Hope', src: 'Hope_card_art.jpg' },
    { title: 'House of Mirrors', src: 'House_of_Mirrors_card_art.jpg' },
    { title: 'Hubris', src: 'Hubris_card_art.jpg' },
    { title: 'Humility', src: 'Humility_card_art.jpg' },
    { title: 'Hunters Resolve', src: 'Hunters_Resolve_card_art.jpg' },
    { title: 'Hunters Reward', src: 'Hunters_Reward_card_art.jpg' },
    { title: 'Immortal Resolve', src: 'Immortal_Resolve_card_art.jpg' },
    { title: 'Imperial Legacy', src: 'Imperial_Legacy_card_art.jpg' },
    { title: 'Jack in the Box', src: 'Jack_in_the_Box_card_art.jpg' },
    { title: 'Lantadors Lost Love', src: 'Lantadors_Lost_Love_card_art.jpg' },
    { title: 'Last Hope', src: 'Last_Hope_card_art.jpg' },
    { title: 'Left to Fate', src: 'Left_to_Fate_card_art.jpg' },
    { title: 'Light and Truth', src: 'Light_and_Truth_card_art.jpg' },
    { title: 'Lingering Remnants', src: 'Lingering_Remnants_card_art.jpg' },
    { title: 'Lost Worlds', src: 'Lost_Worlds_card_art.jpg' },
    { title: 'Loyalty', src: 'Loyalty_card_art.jpg' },
    { title: 'Lucky Connections', src: 'Lucky_Connections_card_art.jpg' },
    { title: 'Lucky Deck', src: 'Lucky_Deck_card_art.jpg' },
    { title: 'Lysahs Respite', src: 'Lysahs_Respite_card_art.jpg' },
    { title: 'Mawr Blaidd', src: 'Mawr_Blaidd_card_art.jpg' },
    { title: 'Merciless Armament', src: 'Merciless_Armament_card_art.jpg' },
    { title: 'Might is Right', src: 'Might_is_Right_card_art.jpg' },
    { title: 'Mitts', src: 'Mitts_card_art.jpg' },
    { title: 'Monochrome', src: 'Monochrome_card_art.jpg' },
    { title: 'More is Never Enough', src: 'More_is_Never_Enough_card_art.jpg' },
    { title: 'No Traces', src: 'No_Traces_card_art.jpg' },
    { title: 'Nooks Crown', src: 'Nooks_Crown_card_art.jpg' },
    { title: 'Perfection', src: 'Perfection_card_art.jpg' },
    { title: 'Pride Before the Fall', src: 'Pride_Before_the_Fall_card_art.jpg' },
    { title: 'Pride of the First Ones', src: 'Pride_of_the_First_Ones_card_art.jpg' },
    { title: 'Prosperity', src: 'Prosperity_card_art.jpg' },
    { title: 'Rain of Chaos', src: 'Rain_of_Chaos_card_art.jpg' },
    { title: 'Rain Tempter', src: 'Rain_Tempter_card_art.jpg' },
    { title: 'Rats', src: 'Rats_card_art.jpg' },
    { title: 'Rebirth', src: 'Rebirth_card_art.jpg' },
    { title: 'Remembrance', src: 'Remembrance_card_art.jpg' },
    { title: 'Sambodhis Vow', src: 'Sambodhis_Vow_card_art.jpg' },
    { title: 'Scholar of the Seas', src: 'Scholar_of_the_Seas_card_art.jpg' },
    { title: 'Seven Years Bad Luck', src: 'Seven_Years_Bad_Luck_card_art.jpg' },
    { title: 'Shard of Fate', src: 'Shard_of_Fate_card_art.jpg' },
    { title: 'Squandered Prosperity', src: 'Squandered_Prosperity_card_art.jpg' },
    { title: 'Struck by Lightning', src: 'Struck_by_Lightning_card_art.jpg' },
    { title: 'Succor of the Sinless', src: 'Succor_of_the_Sinless_card_art.jpg' },
    { title: 'The Admirer', src: 'The_Admirer_card_art.jpg' },
    { title: 'The Aesthete', src: 'The_Aesthete_card_art.jpg' },
    { title: 'The Archmages Right Hand', src: 'The_Archmages_Right_Hand_card_art.jpg' },
    { title: 'The Arena Champion', src: 'The_Arena_Champion_card_art.jpg' },
    { title: 'The Army of Blood', src: 'The_Army_of_Blood_card_art.jpg' },
    { title: 'The Artist', src: 'The_Artist_card_art.jpg' },
    { title: 'The Avenger', src: 'The_Avenger_card_art.jpg' },
    { title: 'The Bargain', src: 'The_Bargain_card_art.jpg' },
    { title: 'The Battle Born', src: 'The_Battle_Born_card_art.jpg' },
    { title: 'The Beast', src: 'The_Beast_card_art.jpg' },
    { title: 'The Betrayal', src: 'The_Betrayal_card_art.jpg' },
    { title: 'The Blazing Fire', src: 'The_Blazing_Fire_card_art.jpg' },
    { title: 'The Body', src: 'The_Body_card_art.jpg' },
    { title: 'The Bones', src: 'The_Bones_card_art.jpg' },
    { title: 'The Breach', src: 'The_Breach_card_art.jpg' },
    { title: 'The Brittle Emperor', src: 'The_Brittle_Emperor_card_art.jpg' },
    { title: 'The Cacophony', src: 'The_Cacophony_card_art.jpg' },
    { title: 'The Calling', src: 'The_Calling_card_art.jpg' },
    { title: 'The Carrion Crow', src: 'The_Carrion_Crow_card_art.jpg' },
    { title: 'The Cartographer', src: 'The_Cartographer_card_art.jpg' },
    { title: 'The Catalyst', src: 'The_Catalyst_card_art.jpg' },
    { title: 'The Celestial Justicar', src: 'The_Celestial_Justicar_card_art.jpg' },
    { title: 'The Celestial Stone', src: 'The_Celestial_Stone_card_art.jpg' },
    { title: 'The Chains that Bind', src: 'The_Chains_that_Bind_card_art.jpg' },
    { title: 'The Cheater', src: 'The_Cheater_card_art.jpg' },
    { title: 'The Chosen', src: 'The_Chosen_card_art.jpg' },
    { title: 'The Coming Storm', src: 'The_Coming_Storm_card_art.jpg' },
    { title: 'The Conduit', src: 'The_Conduit_card_art.jpg' },
    { title: 'The Craving', src: 'The_Craving_card_art.jpg' },
    { title: 'The Cursed King', src: 'The_Cursed_King_card_art.jpg' },
    { title: 'The Damned', src: 'The_Damned_card_art.jpg' },
    { title: 'The Dapper Prodigy', src: 'The_Dapper_Prodigy_card_art.jpg' },
    { title: 'The Dark Mage', src: 'The_Dark_Mage_card_art.jpg' },
    { title: 'The Darkest Dream', src: 'The_Darkest_Dream_card_art.jpg' },
    { title: 'The Deal', src: 'The_Deal_card_art.jpg' },
    { title: 'The Deceiver', src: 'The_Deceiver_card_art.jpg' },
    { title: 'The Deep Ones', src: 'The_Deep_Ones_card_art.jpg' },
    { title: 'The Demon', src: 'The_Demon_card_art.jpg' },
    { title: 'The Demoness', src: 'The_Demoness_card_art.jpg' },
    { title: 'The Doctor', src: 'The_Doctor_card_art.jpg' },
    { title: 'The Doppelganger', src: 'The_Doppelganger_card_art.jpg' },
    { title: 'The Dragons Heart', src: 'The_Dragons_Heart_card_art.jpg' },
    { title: 'The Dragon', src: 'The_Dragon_card_art.jpg' },
    { title: 'The Dreamer', src: 'The_Dreamer_card_art.jpg' },
    { title: 'The Dreamland', src: 'The_Dreamland_card_art.jpg' },
    { title: 'The Drunken Aristocrat', src: 'The_Drunken_Aristocrat_card_art.jpg' },
    { title: 'The Easy Stroll', src: 'The_Easy_Stroll_card_art.jpg' },
    { title: 'The Eldritch Decay', src: 'The_Eldritch_Decay_card_art.jpg' },
    { title: 'The Encroaching Darkness', src: 'The_Encroaching_Darkness_card_art.jpg' },
    { title: 'The Endless Darkness', src: 'The_Endless_Darkness_card_art.jpg' },
    { title: 'The Endurance', src: 'The_Endurance_card_art.jpg' },
    { title: 'The Enlightened', src: 'The_Enlightened_card_art.jpg' },
    { title: 'The Escape', src: 'The_Escape_card_art.jpg' },
    { title: 'The Ethereal', src: 'The_Ethereal_card_art.jpg' },
    { title: 'The Explorer', src: 'The_Explorer_card_art.jpg' },
    { title: 'The Eye of Terror', src: 'The_Eye_of_Terror_card_art.jpg' },
    { title: 'The Eye of the Dragon', src: 'The_Eye_of_the_Dragon_card_art.jpg' },
    { title: 'The Fathomless Depths', src: 'The_Fathomless_Depths_card_art.jpg' },
    { title: 'The Feast', src: 'The_Feast_card_art.jpg' },
    { title: 'The Fiend', src: 'The_Fiend_card_art.jpg' },
    { title: 'The Fishmonger', src: 'The_Fishmonger_card_art.jpg' },
    { title: 'The Fletcher', src: 'The_Fletcher_card_art.jpg' },
    { title: 'The Floras Gift', src: 'The_Floras_Gift_card_art.jpg' },
    { title: 'The Fool', src: 'The_Fool_card_art.jpg' },
    { title: 'The Formless Sea', src: 'The_Formless_Sea_card_art.jpg' },
    { title: 'The Forsaken', src: 'The_Forsaken_card_art.jpg' },
    { title: 'The Fox', src: 'The_Fox_card_art.jpg' },
    { title: 'The Gambler', src: 'The_Gambler_card_art.jpg' },
    { title: 'The Garish Power', src: 'The_Garish_Power_card_art.jpg' },
    { title: 'The Gemcutter', src: 'The_Gemcutter_card_art.jpg' },
    { title: 'The Gentleman', src: 'The_Gentleman_card_art.jpg' },
    { title: 'The Gladiator', src: 'The_Gladiator_card_art.jpg' },
    { title: 'The Golden Era', src: 'The_Golden_Era_card_art.jpg' },
    { title: 'The Hale Heart', src: 'The_Hale_Heart_card_art.jpg' },
    { title: 'The Harvester', src: 'The_Harvester_card_art.jpg' },
    { title: 'The Hermit', src: 'The_Hermit_card_art.jpg' },
    { title: 'The Heroic Shot', src: 'The_Heroic_Shot_card_art.jpg' },
    { title: 'The Hoarder', src: 'The_Hoarder_card_art.jpg' },
    { title: 'The Hunger', src: 'The_Hunger_card_art.jpg' },
    { title: 'The Immortal', src: 'The_Immortal_card_art.jpg' },
    { title: 'The Incantation', src: 'The_Incantation_card_art.jpg' },
    { title: 'The Innocent', src: 'The_Innocent_card_art.jpg' },
    { title: 'The Inoculated', src: 'The_Inoculated_card_art.jpg' },
    { title: 'The Insatiable', src: 'The_Insatiable_card_art.jpg' },
    { title: 'The Inventor', src: 'The_Inventor_card_art.jpg' },
    { title: 'The Iron Bard', src: 'The_Iron_Bard_card_art.jpg' },
    { title: 'The Jester', src: 'The_Jester_card_art.jpg' },
    { title: 'The Jewellers Boon', src: 'The_Jewellers_Boon_card_art.jpg' },
    { title: 'The Journey', src: 'The_Journey_card_art.jpg' },
    { title: 'The Kings Blade', src: 'The_Kings_Blade_card_art.jpg' },
    { title: 'The Kings Heart', src: 'The_Kings_Heart_card_art.jpg' },
    { title: 'The Landing', src: 'The_Landing_card_art.jpg' },
    { title: 'The Last One Standing', src: 'The_Last_One_Standing_card_art.jpg' },
    { title: 'The Lich', src: 'The_Lich_card_art.jpg' },
    { title: 'The Life Thief', src: 'The_Life_Thief_card_art.jpg' },
    { title: 'The Lion', src: 'The_Lion_card_art.jpg' },
    { title: 'The Lord in Black', src: 'The_Lord_in_Black_card_art.jpg' },
    { title: 'The Lord of Celebration', src: 'The_Lord_of_Celebration_card_art.jpg' },
    { title: 'The Lover', src: 'The_Lover_card_art.jpg' },
    { title: 'The Lunaris Priestess', src: 'The_Lunaris_Priestess_card_art.jpg' },
    { title: 'The Mad King', src: 'The_Mad_King_card_art.jpg' },
    { title: 'The Master Artisan', src: 'The_Master_Artisan_card_art.jpg' },
    { title: 'The Master', src: 'The_Master_card_art.jpg' },
    { title: 'The Mayor', src: 'The_Mayor_card_art.jpg' },
    { title: 'The Mercenary', src: 'The_Mercenary_card_art.jpg' },
    { title: 'The Messenger', src: 'The_Messenger_card_art.jpg' },
    { title: 'The Metalsmiths Gift', src: 'The_Metalsmiths_Gift_card_art.jpg' },
    { title: 'The Mountain', src: 'The_Mountain_card_art.jpg' },
    { title: 'The Nurse', src: 'The_Nurse_card_art.jpg' },
    { title: 'The Oath', src: 'The_Oath_card_art.jpg' },
    { title: 'The Obscured', src: 'The_Obscured_card_art.jpg' },
    { title: 'The Offering', src: 'The_Offering_card_art.jpg' },
    { title: 'The Old Man', src: 'The_Old_Man_card_art.jpg' },
    { title: 'The One With All', src: 'The_One_With_All_card_art.jpg' },
    { title: 'The Opulent', src: 'The_Opulent_card_art.jpg' },
    { title: 'The Pack Leader', src: 'The_Pack_Leader_card_art.jpg' },
    { title: 'The Pact', src: 'The_Pact_card_art.jpg' },
    { title: 'The Penitent', src: 'The_Penitent_card_art.jpg' },
    { title: 'The Poet', src: 'The_Poet_card_art.jpg' },
    { title: 'The Polymath', src: 'The_Polymath_card_art.jpg' },
    { title: 'The Porcupine', src: 'The_Porcupine_card_art.jpg' },
    { title: 'The Price of Loyalty', src: 'The_Price_of_Loyalty_card_art.jpg' },
    { title: 'The Price of Protection', src: 'The_Price_of_Protection_card_art.jpg' },
    { title: 'The Primordial', src: 'The_Primordial_card_art.jpg' },
    { title: 'The Professor', src: 'The_Professor_card_art.jpg' },
    { title: 'The Progeny of Lunaris', src: 'The_Progeny_of_Lunaris_card_art.jpg' },
    { title: 'The Puzzle', src: 'The_Puzzle_card_art.jpg' },
    { title: 'The Queen', src: 'The_Queen_card_art.jpg' },
    { title: 'The Rabid Rhoa', src: 'The_Rabid_Rhoa_card_art.jpg' },
    { title: 'The Realm', src: 'The_Realm_card_art.jpg' },
    { title: 'The Risk', src: 'The_Risk_card_art.jpg' },
    { title: 'The Rite of Elements', src: 'The_Rite_of_Elements_card_art.jpg' },
    { title: 'The Road to Power', src: 'The_Road_to_Power_card_art.jpg' },
    { title: 'The Ruthless Ceinture', src: 'The_Ruthless_Ceinture_card_art.jpg' },
    { title: 'The Sacrifice', src: 'The_Sacrifice_card_art.jpg' },
    { title: 'The Saints Treasure', src: 'The_Saints_Treasure_card_art.jpg' },
    { title: 'The Samurais Eye', src: 'The_Samurais_Eye_card_art.jpg' },
    { title: 'The Scarred Meadow', src: 'The_Scarred_Meadow_card_art.jpg' },
    { title: 'The Scavenger', src: 'The_Scavenger_card_art.jpg' },
    { title: 'The Scholar', src: 'The_Scholar_card_art.jpg' },
    { title: 'The Seeker', src: 'The_Seeker_card_art.jpg' },
    { title: 'The Sephirot', src: 'The_Sephirot_card_art.jpg' },
    { title: 'The Side Quest', src: 'The_Side_Quest_card_art.jpg' },
    { title: 'The Sigil', src: 'The_Sigil_card_art.jpg' },
    { title: 'The Siren', src: 'The_Siren_card_art.jpg' },
    { title: 'The Skeleton', src: 'The_Skeleton_card_art.jpg' },
    { title: 'The Soul', src: 'The_Soul_card_art.jpg' },
    { title: 'The Spark and the Flame', src: 'The_Spark_and_the_Flame_card_art.jpg' },
    { title: 'The Spoiled Prince', src: 'The_Spoiled_Prince_card_art.jpg' },
    { title: 'The Standoff', src: 'The_Standoff_card_art.jpg' },
    { title: 'The Stormcaller', src: 'The_Stormcaller_card_art.jpg' },
    { title: 'The Strategist', src: 'The_Strategist_card_art.jpg' },
    { title: 'The Summoner', src: 'The_Summoner_card_art.jpg' },
    { title: 'The Sun', src: 'The_Sun_card_art.jpg' },
    { title: 'The Surgeon', src: 'The_Surgeon_card_art.jpg' },
    { title: 'The Surveyor', src: 'The_Surveyor_card_art.jpg' },
    { title: 'The Survivalist', src: 'The_Survivalist_card_art.jpg' },
    { title: 'The Sword Kings Salute', src: 'The_Sword_Kings_Salute_card_art.jpg' },
    { title: 'The Thaumaturgist', src: 'The_Thaumaturgist_card_art.jpg' },
    { title: 'The Throne', src: 'The_Throne_card_art.jpg' },
    { title: 'The Tinkerers Table', src: 'The_Tinkerers_Table_card_art.jpg' },
    { title: 'The Tower', src: 'The_Tower_card_art.jpg' },
    { title: 'The Traitor', src: 'The_Traitor_card_art.jpg' },
    { title: 'The Trial', src: 'The_Trial_card_art.jpg' },
    { title: 'The Twilight Moon', src: 'The_Twilight_Moon_card_art.jpg' },
    { title: 'The Twins', src: 'The_Twins_card_art.jpg' },
    { title: 'The Tyrant', src: 'The_Tyrant_card_art.jpg' },
    { title: 'The Undaunted', src: 'The_Undaunted_card_art.jpg' },
    { title: 'The Undisputed', src: 'The_Undisputed_card_art.jpg' },
    { title: 'The Union', src: 'The_Union_card_art.jpg' },
    { title: 'The Valkyrie', src: 'The_Valkyrie_card_art.jpg' },
    { title: 'The Valley of Steel Boxes', src: 'The_Valley_of_Steel_Boxes_card_art.jpg' },
    { title: 'The Vast', src: 'The_Vast_card_art.jpg' },
    { title: 'The Visionary', src: 'The_Visionary_card_art.jpg' },
    { title: 'The Void', src: 'The_Void_card_art.jpg' },
    { title: 'The Warden', src: 'The_Warden_card_art.jpg' },
    { title: 'The Warlord', src: 'The_Warlord_card_art.jpg' },
    { title: 'The Watcher', src: 'The_Watcher_card_art.jpg' },
    { title: 'The Web', src: 'The_Web_card_art.jpg' },
    { title: 'The Wilted Rose', src: 'The_Wilted_Rose_card_art.jpg' },
    { title: 'The Wind', src: 'The_Wind_card_art.jpg' },
    { title: 'The Witch', src: 'The_Witch_card_art.jpg' },
    { title: 'The Wolfs Legacy', src: 'The_Wolfs_Legacy_card_art.jpg' },
    { title: 'The Wolfs Shadow', src: 'The_Wolfs_Shadow_card_art.jpg' },
    { title: 'The Wolf', src: 'The_Wolf_card_art.jpg' },
    { title: 'The Wolven Kings Bite', src: 'The_Wolven_Kings_Bite_card_art.jpg' },
    { title: 'The Wolverine', src: 'The_Wolverine_card_art.jpg' },
    { title: 'The World Eater', src: 'The_World_Eater_card_art.jpg' },
    { title: 'The Wrath', src: 'The_Wrath_card_art.jpg' },
    { title: 'The Wretched', src: 'The_Wretched_card_art.jpg' },
    { title: 'Thirst for Knowledge', src: 'Thirst_for_Knowledge_card_art.jpg' },
    { title: 'Three Faces in the Dark', src: 'Three_Faces_in_the_Dark_card_art.jpg' },
    { title: 'Three Voices', src: 'Three_Voices_card_art.jpg' },
    { title: 'Thunderous Skies', src: 'Thunderous_Skies_card_art.jpg' },
    { title: 'Time-Lost Relic', src: 'Time-Lost_Relic_card_art.jpg' },
    { title: 'Tranquillity', src: 'Tranquillity_card_art.jpg' },
    { title: 'Treasure Hunter', src: 'Treasure_Hunter_card_art.jpg' },
    { title: 'Turn the Other Cheek', src: 'Turn_the_Other_Cheek_card_art.jpg' },
    { title: 'Underground Forest', src: 'Underground_Forest_card_art.jpg' },
    { title: 'Vanity', src: 'Vanity_card_art.jpg' },
    { title: 'Vile Power', src: 'Vile_Power_card_art.jpg' },
    { title: 'Vinias Token', src: 'Vinias_Token_card_art.jpg' },
    { title: 'Void of the Elements', src: 'Void_of_the_Elements_card_art.jpg' },
    { title: 'Volatile Power', src: 'Volatile_Power_card_art.jpg' },
    { title: 'Wealth and Power', src: 'Wealth_and_Power_card_art.jpg' }
  ]
})
